version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: mqtt-service/Dockerfile
      args:
        serviceName: mqtt-service
    image: mqtt-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
